### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by SherrySwift** [ThisisBillhe/ZipCache#2]
Hi, thanks for your great work. Is there any plan to release the full evaluation code on GSM8K and Line Retrival?

**Comment by ThisisBillhe** [comment]
Hi, we use [lm_eval](https://github.com/EleutherAI/lm-evaluation-harness) to evaluate GSM8k and [longeval](https://github.com/DachengLi1/LongChat) to evaluate Line Retrieval.

**Comment by SherrySwift** [comment]
Thanks for your reply!
I have another question. According to paper, 10% probe tokens are selected for attention scores computation. But in [code](https://github.com/ThisisBillhe/ZipCache/blob/b6932b99bacbc4c3a55747b4e55d4ea2ae477a22/zipcache/models/modeling_llama.py#L802), it seems that during decoding phase, only 1 probe token is selected in every 100 steps, rather than 10 probe tokens.
Please correct me if I misunderstand something. Thanks a lot!

**Comment by wengmaochi** [comment]
Hi @SherrySwift , I am trying to reproduce the number for llama-3-8B on GSM8K. Did you manage to get 53.75? Thanks!
